[project]
name = "ckanext-dietstars"
version = "0.0.1"
description = "Diet Stars"
readme = "README.rst"
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 5 - Production",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = [
    "ckan",
    "ckanext",
    "qa",
    "openness",
    "stars"
]

[project.urls]
Repository = "https://github.com/derilinx/ckanext-dietstars"
Issues = "https://github.com/derilinx/ckanext-dietstars/issues"

[build-system]
requires = ["setuptools>=62.6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["ckanext*"]

[project.entry-points."ckan.plugins"]
dietstars = "ckanext.dietstars.plugin:DietStarsPlugin"

[project.entry-points."babel.extractors"]
ckan = "ckan.lib.extract:extract_ckan"
